### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by Evizero** [JuliaImages/ImageDistances.jl#1]
@juliohm I didn't want to take the liberty to write your name into the license, so I defer this to you. I removed mine which was just placed there by PkgDev on generation.

**Comment by juliohm** [comment]
Thank you, I will take care of it :+1: I am currently using PkgTemplates.jl instead of PkgDev.jl because it is more flexible:

```julia
using PkgTemplates
generate_interactive("MyPkg")
```

**Comment by Evizero** [comment]
If you wish to generate the package fresh feel free to do so and force push. I suppose it wasn't really necessary for me to generate the content now that I think about it. I just didn't question my first instinct for "setting up a repository"

**Comment by juliohm** [comment]
No problem at all, everything is perfect :)
