### ISSUE TITLE
README `evaluate` example not working

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaImages/ImageDistances.jl#15]
```julia
using Images, ImageDistances

img1 = rand(640,480); 
img2 = rand(640,480);

d = ModifiedHausdorff()

# distance between two images
evaluate(d, imgA, imgB) # 

hausdorff(img1, img2) # works but gives 0
```

**Comment by juliohm** [comment]
@johnnychen94 could you please take a look at this? I know you've been reviewing the code recently... I am guessing that the error has something to do with the fact that we are not importing `Distances` anymore.

Also, could you please submit a PR adding a comment that Hausdorff distances are only defined for black and white images?

@xiaodaigh could you please confirm that `hausdorff(rand(0:1, 100,100), rand(0:1, 100, 100)` returns something different than zero?

**Comment by xiaodaigh** [comment]
I do get `0` after running `hausdorff(rand(0:1, 100,100), rand(0:1, 100, 100))`. In fact I get

```julia
julia> hausdorff(rand(0:1, 100,100), rand(0:1, 100, 100))
┌ Warning: implicit `dims=2` argument now has to be passed explicitly to specify that distances between columns should be computed
│   caller = ip:0x0
└ @ Core :-1
0.0
```

**Comment by johnnychen94** [comment]
Sure I’ll check it after I finished the redesign part. There’s some issue in my PR to Distances.jl, I need to think it carefully.

Johnny
On Apr 29, 2019, 19:28 +0800, evalparse <notifications@github.com>, wrote:

I do get 0 after running hausdorff(rand(0:1, 100,100), rand(0:1, 100, 100)). In fact I get

julia> hausdorff(rand(0:1, 100,100), rand(0:1, 100, 100))

┌ Warning: implicit `dims=2` argument now has to be passed explicitly to specify that distances between columns should be computed

│   caller = ip:0x0

└ @ Core :-1

0.0

**Comment by johnnychen94** [comment]
> could you please submit a PR adding a comment that Hausdorff distances are only defined for black and white images?

@juliohm you mean it's `AbstractArray{Bool}` type?

**Comment by juliohm** [comment]
Maybe we should consider restricting it to AbstractArray{Bool}, I do not
remember the types I used in the implementation.

Typing very quickly without actually looking into the code. Very busy week
around here...

Em seg, 29 de abr de 2019 às 12:14, Johnny Chen <notifications@github.com>
escreveu:

**Comment by johnnychen94** [comment]
> I am guessing that the error has something to do with the fact that we are not importing Distances anymore.

I've checked the `ImageDistances@0.1.0`, which is prior to my fix PR "remove unnecessary dependency on Distances" #8. Got the same `0.0` result. Perhaps we need to revisit the implementations.

**Comment by juliohm** [comment]
The warning in the example above in one of the previous comments is
suspicious. Probably the bug is due to the update in distances.jl where it
is now important to specify dim=2 or something... i can try take a look
tomorrow if you can't find the bug earlier. Are the tests passing?

**Comment by juliohm** [comment]
@xiaodaigh sorry for the problem you had. I had incorrectly assigned the wrong reduction operation in the Hausdorff definition. When I wrote this package I only used ModifiedHausdorff() because it was shown to be superior in speed and object matching (see Dubuisson). I have now fixed the definition of Hausdorff in the code.

We should tag a patch release for this bug @johnnychen94 :+1:
