### ISSUE TITLE
move diff-related functions to ImageDistances.jl

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageDistances.jl#17]
Cont. https://github.com/JuliaImages/Images.jl/issues/729

This helps remove the `Images.jl` dependency in `ReferenceTest`

- [x] port `sad`, `ssd`, `sadn`, `ssdn` #30 #35
- [x] port `ncc` #35
- [ ] deprecate `wnorm2` in favor of `WeightedMinkowski`
- [x] port `test_approx_eq_sigma_eps` (perhaps rewrite it to reduce dependency) -- https://github.com/Evizero/ReferenceTests.jl/pull/31

**Comment by juliohm** [comment]
Thank you @johnnychen94 for that. It would be nice to see the whole set of distances in Images.jl moved to ImageDistances.jl

**Comment by johnnychen94** [comment]
Shipped with Images v0.19
