### ISSUE TITLE
Performance benchmark

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageDistances.jl#27]
I didn't consider the performance much in the current implementation, but we will definitely need optimizations before the next minor release.

Before #22 , it would be convenient to provide a benchmark tool. Also post the benchmark results just like https://github.com/JuliaStats/Distances.jl#benchmarks

**Comment by ashwani-rathee** [comment]
Since I have to study Image distances in next few weeks, it would be good if we can resolve this.
something like https://github.com/JuliaStats/Distances.jl/blob/master/benchmark/benchmarks.jl is what we are looking for.

**Comment by johnnychen94** [comment]
Keep safe from the COVID-19!

**Comment by johnnychen94** [comment]
should be resolved by #66
