### ISSUE TITLE
Hausdorff uses O(n^2) space and time, making it impractical for dense images

### ISSUE THREAD

**Issue by jsenn** [JuliaImages/ImageDistances.jl#56]
For example, the following throws an OutOfMemory error on my machine:
```julia
using Random
hausdorff(bitrand(640, 480), bitrand(640, 480))
```
The following uses existing routines from the Images package to do the calculation:
```julia
function hausdorff(A::BitArray{2}, B::BitArray{2})
    dtA = distance_transform(feature_transform(A))
    dtB = distance_transform(feature_transform(B))
    dAB = maximum(A .* dtB)
    dBA = maximum(B .* dtA)
    return max(dAB, dBA)
end
```
The run time and space complexity of this is implementation are linear in the size of the images, where the existing implementation is quadratic (in the number of non-background points that is, so it might be faster for large sparse images).

As an illustration of the efficiency gains, it takes about 1.5s to diff 2 random 4k images (3800x2200) on my machine with the `distance_transform` implementation, which is about how long it takes to diff 2 random 125x125 images with the existing implementation.

If you're interested I could take a crack at submitting a PR.

**Comment by juliohm** [comment]
Hi @jsenn can you clarify how the code is equivalent to the existing implementation? I am not up-to-date with the latest version of `feature_transform` and and `distance_transform`, nor can see how the `maximum(A .* dtB)` is equivalent to `dAB = _reduce(d.inner_op, minimum(D, dims=2))` in the code base where `D` is the pairwise Euclidean matrix between the active pixels in A and B.

**Comment by jsenn** [comment]
@juliohm yeah, sorry I should have been clear about what that code was actually doing :). `feature_transform` gives you, for every pixel in the image, the coordinates of the nearest active pixel. `distance_transform` takes those coordinates and computes actual distances out of them. So `dtA`, for example, contains, for every pixel in the image, the distance from that pixel to the closest active pixel in `A`. Likewise for `dtB`.

The result of `A .* dtB` is an array with the same size as our input images. For each pixel p, if that pixel is non-active in `A`, then it will have a value of 0 in this new array (because it's multiplied by the 0 value from `A`). If pixel p is active in `A` however, the value in the new array will be the distance from that pixel to the nearest pixel in `B`, fetched from `dtB`. The maximum value in this array is then the largest distance from an active pixel in `A` to the nearest pixel in `B` (that is, it's the one-way Hausdorff distance from `A` to `B`).

The algorithm does the same operation from `B` to `A`, and returns the larger of the 2 (i.e., it computes the "2-way" Hausdorff distance).

This should give the same result as the existing implementation, but as I noted it operates on dense arrays, rather than sparse arrays, so there may be some large and sparse images where the existing implementation is better.

Just to make sure, I tested this against the existing implementation with 1,000 random 50x50 images, and they always returned exactly the same result.

**Comment by juliohm** [comment]
That is a very clear explanation @jsenn , thanks for putting the time to write it up. I'be happy to review a PR. It is a great trick and improvement of performance. 💯 We just need to make sure that we preserve the generality of he distances with the inner and outer ops inside of the struct. This operation you are describing is the original `Hausdorff` distance without `mean` approximations in the `ModifiedHausdorff`. So the PR should probably only touch the `Hausdorff` part.
