### ISSUE TITLE
Mean Hausdorff

### ISSUE THREAD

**Issue by Dale-Black** [JuliaImages/ImageDistances.jl#62]
I need to implement a mean hausdorff metric for my own studies and I figured it would be more helpful if I added it to this repo for usability. Would this be of interest?

**Comment by juliohm** [comment]
I think we already have a mean Hausdorff. Can you elaborate on your definition? Check our GenericHausdorff, it is flexible about the inner and outer operations. Maybe you are referring to the ModifiedHausdorff we already export.

**Comment by Dale-Black** [comment]
Oh, so for GenericHausdorff one could input `mean()` for the outer operation to turn it into a mean hausdorff metric?

**Comment by juliohm** [comment]
Yep: https://github.com/JuliaImages/ImageDistances.jl/blob/d5ee1d90e9cffcb57c3e715839bbe6b577611da8/src/hausdorff.jl#L84-L85

**Comment by Dale-Black** [comment]
Looks like my problem is solved, thank you! Is there a way I could contribute by making this clearer in the docs at all?

**Comment by johnnychen94** [comment]
> Is there a way I could contribute by making this clearer in the docs at all?

Provide an example in README.md would be very much helpful!
