### ISSUE TITLE
redesign the type hierarchy

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageDistances.jl#7]
Currently
```julia
# in Distances.jl
abstract type PreMetric end
abstract type SemiMetric <: PreMetric end
abstract type Metric <: SemiMetric end

# in ImageDistances.jl
abstract type ImagePreMetric end
abstract type ImageSemiMetric <: ImagePreMetric end
abstract type ImageMetric <: ImageSemiMetric end
```
Types in `Distances` and `ImageDistances` are independent.

If we want to use codes from `Distances` package, I think an easier path is to define
```julia
abstract type ImagePreMetric <: Distances.PreMetric end
abstract type ImageSemiMetric <: Distances.SemiMetric end
abstract type ImageMetric <: Distances.Metric end
```
so that we only need to handle two special types: `Normed` and `Colorant`

**Comment by juliohm** [comment]
Lovely! I think it makes sense. Thanks for the insights. Could you please submit a PR for this change? I'd happy to review and merge.

**Comment by johnnychen94** [comment]
I'm willing to, perhaps one or two weeks later. In the meantime, I might need your help since I don't quite understand how `Hausdauff` works ( If I need to change the code).

The PR https://github.com/JuliaImages/ImageDistances.jl/pull/6 will be paused until this's done.

**Comment by juliohm** [comment]
Sure, I'd be happy to help. Please let me know how the implementation of Hausdorff conflicts with the proposed change, and we will work together to make it work.

Thanks for the time again. I am looking forward to it.

**Comment by johnnychen94** [comment]
After some investigation, I can't see the advantages of introducing another `ImagePreMetric` type.
Directly implement image-specific functions based on `Distances` is enough.

related PR: https://github.com/JuliaStats/Distances.jl/pull/128
